[project]
name = "pydantic-examples"
version = "0.1.0"
description = "Generate examples of serialized data from Pydantic models"
authors = [
    { name = "Bram Neijt", email = "bram@neijt.nl" }
]
dependencies = [
    "ruamel-yaml>=0.18.6",
    "pydantic>=2.9.2",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.3.3",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/pydantic_examples"]
